### NorthPay Backend - Authentication API

@baseUrl = http://localhost:3000/api/v1

### Endpoint Seed Admin
# Este endpoint se utiliza para crear un usuario admin por defecto en la base de datos. Solo

POST {{baseUrl}}/seed/seed-admin
Content-Type: application/json

### Login User
# Aquí el User se "Loggea" hacia la plataforma
POST {{baseUrl}}/login
Content-Type: application/json

{
    "email": "repollo@gmail.com",
    "password": "superPassssszzz"
}
### Register User
# Registra al usuario independientemente de su rol (validación básica)
POST {{baseUrl}}/register
Content-Type: application/json

{
    "email": "repollo@gmail.com",
    "password": "superPassssszzz",
    "role": "contractor",
    "firstname": "Northpay",
    "lastname": "Practice Contractor",
    "phone": "+5835246246523523"
}

### Send Magic Link
# Creación y envío de Link de acceso para nuevos Usuarios Contratistas
POST {{baseUrl}}/magicLink
Content-Type: application/json

{
    "method": "email",
    "receiver": {
        "number": "+584264000136",
        "username": "Dexter",
        "email": "something35@gmail.com"
    },
    "operatorId": "f0fc0f44-b48f-4f56-99dc-6b59e4897b0a",
    "adminId": "aa4633d2-38cb-4dd2-a279-409bebf0c47a"
}