### NorthPay Backend - Test API

@baseUrl = http://localhost:3001

### Login User
# Aquí el User se "Loggea" hacia la plataforma
POST {{baseUrl}}/login
Content-Type: application/json

{
    "email": "something3@gmail.com",
    "password": "superSecurepassword132"
}
### Register User
# Registra al usuario independientemente de su rol (validación básica)
POST {{baseUrl}}/register
Content-Type: application/json

{
    "email": "something3@gmail.com",
    "password": "superSecurepassword132",
    "role": "contractor",
    "firstname": "Mr",
    "lastname": "Glass",
    "phone": "+594353582975372"
}
### Health Check & Database Connection
# Verifica si el servidor está corriendo y si hay conexión con PostgreSQL
GET {{baseUrl}}/health
Accept: application/json

### Admin Check
# Verifica si el usuario administrador por defecto existe en la base de datos
GET {{baseUrl}}/admin-check
Accept: application/json

### Ejemplos adicionales (Futuros endpoints)

# GET {{baseUrl}}/users
# Accept: application/json

# POST {{baseUrl}}/auth/login
# Content-Type: application/json
# {
#   "email": "test@northpay.com",
#   "password": "password123"
# }
